openapi: 3.0.3
info:
  title: Menthal Health App API
  version: 1.0.0
  description: This is a small software project designed to enhance mental well-being by providing users with activity recommendations based on the current weather.This web application is specifically tailored for Vienna, offering personalized suggestions to help users make the most of their day, regardless of the weather conditions.
paths:
  /weather:
    get:
      summary: Get the current weather in Vienna
      description: |
        This endpoint provides the current weather in Vienna, which is used to generate personalized activity recommendations for users. The weather data is mapped to a set of predefined and simple descriptions such as sunny, cloudy, rainy, windy, or snowy.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Weather"
  /recommendations(energy_level={energy_level};interest={interest}):
    get:
      summary: Get activity recommendations based on the current weather in Vienna and the user's preferences
      description: |
        The user's energy level and interests are used to generate personalized activity recommendations based on the current weather in Vienna. The recommendations are designed to help users make the most of their day, regardless of the weather conditions.
      parameters:
        - in: path
          name: energy_level
          required: true
          description: The user's energy level (very low, low, medium, high, very high)
          schema:
            type: string
        - in: path
          name: interest
          required: true
          description: The user's interest in activities (currently outdoor, home, yoga, meditation, fitness)
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recommendations"
  /feedback:
    post:
      summary: Post feedback on the activity recommendations
      description: |
        This endpoint allows users to provide feedback on the activity recommendations they received. Users can rate the recommendations and provide additional comments to help improve the personalized suggestions.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Feedback"
      responses:
        "201":
          description: Created

components:
  schemas:
    Weather:
      type: object
      properties:
        city:
          type: string
          description: The city for which the weather is being reported (currently fixed to Vienna)
        weather:
          type: string
          description: The current weather in Vienna - e.g. sunny, cloudy, rainy, windy or snowy
    Recommendations:
      type: object
      properties:
        activity:
          type: string
          description: The recommended activity based on the current weather and the user's preferences
    Feedback:
      type: object
      properties:
        rating:
          type: number
          description: The user's rating of the activity recommendations
        comments:
          type: string
          description: The user's comments on the activity recommendations
        email:
          type: string
          description: The user's email address for follow-up communication
